# Generated by Django 4.1.1 on 2023-02-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hopitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sulg', models.SlugField(default='')),
                ('urgence', models.CharField(max_length=10, unique=True)),
                ('localisation', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploadHospital/')),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_ajout',),
            },
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('categorie', models.CharField(choices=[('mat', 'Maternite'), ('sec', 'Secours'), ('sex', 'Sexualite'), ('div', 'Divers')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maladies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomes', models.CharField(choices=[], max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
